    <?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

if ( ! function_exists('element'))
{
	
	function get_lang($eti){
		$CI =& get_instance();
		$CI->load->library("session");
		
		$english = array("spanish"                                              => "Spanish",
						"english"				=> "English",
						"inicio"				=> "Home",
						"quienes-somos"                         => "About Us",
						"servicios"				=> "Services",
						"contacto"				=> "Contact",
						"productos"				=> "Products",
						"eslogan"				=> "Solutions of contructión only for you",
						"nuestros-productos"                    => "Know our product",
						"direccion"				=> "Address",
						"desarrollado-por"                      => "Develop By",
						"nuestros-productos"                    => "Our Products",
						"hecha-un-vistazo-nuestros-productos"	=> "Check out some of our products and see what we have for you !. <br> The best variety in plastic products with the best quality and unbeatable prices",
						"contenido"				=> "Content",
						"sin-productos-destacados"              => "No featured products",
						"etiquetas"				=> "Tags",
						"perfiles-sociales"                     => "Social perfil",
						"complete-formulario-contacto"          => "Complete the contact form with the required information and we will contact you to possible bravedad!",
						"formulario_contacto"                   => "Contact Form",
						"nuestra-ubicacion"                     => "Our Location",
						"nombre-completo"                       => "Full Name",
						"telefono"				=> "Phone",
						"email"					=> "Email",
						"enviar-mensaje"                        => "Send Menssage",
						"mensaje"				=> "Menssage",
						"idiomas"				=> "Language",
						"ver-mas"				=> "View More",
						"productos"				=> "Produts",
						"todas"					=> "All",
						"conoce-mas-sobre-nosotros"             => "Learn more about us",
						"precio"				=> "Price",
						"categoria"				=> "Category",
						"asunto"				=> "Subject",
                                                "clientes"                              => "Costums",
                                                "obras"                                 => "Works",
                                                "cotizacion"                            => "Quotation",
                                                "agregar-carrito"                       => "Add to cart",
                                                "carrito"                               => "Your Cars",
                                                "rif"                                   => "Rif o CI",
                                                "productos-similares"                   => "Similar Prodcts",
                                                "producto-agregado-exito"               => "Product successfully added to cart",
                                                "producto-agregado-error"               => "Sorry, there was an error and the product could not be added",
                                                "msj-carrito"                           => "Complete your truck and send orders in a short time we will contact you",
                                                "total"                                 => "Total",
                                                "seguir-comprando"                      => "Continue Shopping",
                                                "no-hay-productos-carrito"              => "Don't have products in your shopping car",
                                                "cargue-productos"                      => "To send the listing application must load products to the cart",
                                                "solicitar-cotizacion"                  => "Request quote",
                                                "formulario-solicitud"                  => "Application form",
                                                "solicitud-cotizacion-exito"            => "The request for quotation was sent successfully",
                                                "solicitud-cotizacion-error"            => "Sorry, there was an error and quote request could not be sent, try again later",
                                                "obras"                                 => "Works",
                                                "obras-similares"                       => "Similar Works",
                                                "visitas"                               => "Visits",
                                                "construccion"                          => "Construction",
                                                "remodelacion"                          => "Reshuffle",
                                                "ventadeproductos"                      => "Products Sales",
                                                "asesoria"                              => "Consulting",
                                                "conoce"                                => "Known",
                                                "nuestros-servicios"                    => "Our Services",
                                                "nuestras-obras"                        => "Our Works",
                                                "te-presentamos"                        => "We introduce you",
//                                                "nuestros-productos-destacados"         => "Our Featured Products",
                                                "filtra-por-categoria"                  => "Filter for Category",
                                                "ingrese-nombre"                        => "Enter your name",
                                                "ingrese-email"                         => "Enter your Email",
                                                "ingrese-telefono"                      => "Enter your Phone",
                                                "ingrese-mensaje"                       => "Enter your Message",
                                                "ingrese-rif"                           => "Enter Your RIF / DNI",
                                                "mensaje-footer"                        => "All logos used in this website are registered trademarks of each manufacturer, their use on this page is only to promote their products or to indicate the sale of them.",
                                                "deseas-saber-nosotros"                 => "Want to know a little more about us?",
                                                "contactanos"                           => "Contact Us",
                                                "nuestros-clientes"                           => "Our Costumers",
                                                "completa-formulario-y"                 => "Complete the form and",
                                                "ademas-puedes-contactarnos"            => "You can also contact us by completing the form below",
                                                "sin-productos-categoria"               => "Sorry, we currently have no products registered in this category",
                                                "nuestras-categorias"                   => "Our Category",
                                                "registrate"                            => "Sign Up",
                                                "tienda"                                => "Store",
                                                "mi-cuenta"                            => "My Account",
                                                "checkOut"                            => "CheckOut",
                                                "tenemos"				=> "We have",
						"lo-mejor-para-ti"                      => "The best for you",
						"agregar"                               => "Add",
                                                "nuestros-productos-destacados"         => "Know our Featured Products",
                                                "conoce-sobre-nosotros"                 => "About us",
                                                "crea-una-cuenta"                       => "Create an Account",
                                                "registrar"                             => "To register",
                                                "terminos-condiciones"                  => "By clicking 'register' you agree to the Terms & Conditions",
                                                "estado"                                => "State",
                                                "contrasena"                            => "Password",
                                                "seleccione-pais"                       => "Select a Country",
                                                "codigo"                                => "Code",
                                                "numero"                                => "Number",
                                                "registro-exitoso"                     => "Congratulations, your registration at Sporthouse has been successful!",
                                                "email-existe"                          => "Sorry, this email already exists",
                                                "registro-error"                        => "Sorry, your registration could not be completed, try again!",
                                                "mensaje-exitoso"                        => "The message was successfully sent!",
                                                "mensaje-error"                        => "Sorry, your message could not be sent, please try again later",
                                                "comprar-ahora"                        => "Buy now",
                                                "error-nombre"                          => "Excuse me, you must write a name",
                                                "error-email"                          => "Excuse me, you must write an email",
                                                "error-mensaje"                          => "Excuse me, you must write a message",
                                                "error-codigo"                          => "Excuse me, you must write a phone code",
                                                "error-numero"                          => "Excuse me, you must write a phone number",
                                                "error-rifcedula"                          => "Excuse me, you must write a ballot or rif number",
                                                "error-estado"                          => "Excuse me, you must enter a state",
                                                "error-clave"                          => "Excuse me, you must type a key",
                                                "error-pais"                            => "Excuse me, you must select a country",
                                                "error-direccion"                          => "Excuse me, you must write an address",
                                                "producto-detalle"                        => "Product Details",
                                                "modelo"                            => "Model",
                                                "marca"                            => "Brand",
                                                "nuevos-clientes"                  => "New Customers",
                                                "clientes-registrados"                  => "Registered Customers",
                                                "continuar"                         => "Continue",
                                                "login"                         => "Login",
                                                "login-no-existe"                  => "The access data is not registered in the system",
                                                "login-bloqueado"                  => "Sorry for the user you are trying to login with blocked",
                                                "login-exito"                  => "Welcome to Sporthouse, you can continue browsing through the web!",
                                                "login-error"                  => "Sorry, an error occurred while trying to login, please try again later",
                                                "olvido-contrasena"                         => "Forget Your Password?",
                                                "mostrar"                         => "Show",
                                                "por-pagina"                         => "Per page",
                                                "paginas"                         => "Pages",
                                                "lista-busqueda"                  => "Search List",
                                                "Marca"                  => "Brand",
                                                "anio"                  => "año",
                                                "buscar"                  => "Search",
                                                "carrito-compras"                  => "Shopping Cart",
                                                "forma-pago"                  => "All your orders can be paid through paypal and paypal market",
                                                "completar-pago"                  => "You must be logged in to complete your payment",
                                                "ingresa-aqui"                  => "Enter here!",
                                                "cerrar-sesion"                  => "Sign Off",
                                                "texto-agregar-carrito"                  => "This product will be added to the shopping cart list",
                                                "texto-no-pedidos"                  => "You do not have any orders associated with your account.",
                                                "pedido-numero"                  => "Order number",
                                                "pedido-estatus"                  => "Order Status",
                                                "tus-productos"                  => "Your Products",
                                                "como-comprar"                  => "How to buy",
                                                "texto-como-comprar"                  => "We teach you how to buy",
                                                "create-una-cuenta"                    => "Create an account",
                                                "mi-carrito"                  => "View My Cart",
                                                "texto-login"                  => "Please click to login session",
                                              );

                                                
		
		
		
		
		
		$spaning = array("spanish"                                              => "Español",
						"english"				=> "Ingles",
						"inicio"				=> "Inicio",
						"tenemos"				=> "Tenemos",
						"conoce-sobre-nosotros"                 => "Conoce sobre nosotros",
						"agregar"				=> "Agregar",
						"lo-mejor-para-ti"                      => "Lo mejor para ti",
						"quienes-somos"                         => "Quienes Somos",
						"servicios"				=> "Servicios",
						"contacto"				=> "Contacto",
						"productos"				=> "Productos",
						"productos"				=> "Productos",
						"eslogan"				=> "Soluciones en plastico solo para ti",
						"nuestros-productos"                    => "Nuestros Productos",
						"direccion"				=> "Dirección",
						"desarrollado-por"                      => "Desarrollado Por",
						"nuestros-productos"                    => "Conoce Nuestros Productos",
						"nuestros-productos-destacados"         => "Conoce Nuestros Productos mas Destacados",
						"hecha-un-vistazo-nuestros-productos"	=> "Hecha un vistazo a algunos de nuestros productos y ve lo mejor que tenemos para ti!",
						"contenido"				=> "Contenido",
						"sin-productos-destacados"              => "Sin productos destacados",
						"etiquetas"				=> "Etiquetas",
						"perfiles-sociales"                     => "Perfiles Sociales",
						"complete-formulario-contacto"          => "Complete el formulario de contacto con la información requerida y nos comunicaremos con usted a la bravedad posible!",
						"formulario_contacto"                   => "Formulario de Contacto",
						"nuestra-ubicacion"                     => "Nuestra Ubicación",
						"nombre-completo"                       => "Nombre Completo",
						"telefono"				=> "Teléfono",
						"email"					=> "Correo Electrónico",
						"enviar-mensaje"                        => "Enviar Mensaje",
						"mensaje"				=> "Mensaje",
						"idiomas"				=> "Idiomas",
						"ver-mas"				=> "Ver Mas",
						"productos"				=> "Productos",
						"todas"					=> "Todas",
						"conoce-mas-sobre-nosotros"             => "Conoce mas sobre nosotros",
						"precio"				=> "Precio",
						"categoria"				=> "Categoria",
						"asunto"				=> "Asunto",
                                                "clientes"                              => "Clientes",
                                                "obras"                                 => "Obras",
                                                "cotizacion"                            => "Cotización",
                                                "agregar-carrito"                       => "Agregar al Carrito",
                                                "carrito"                               => "Tu Carro",
                                                "rif"                                   => "Rif o CI",
                                                "productos-similares"                   => "Productos Similares",
                                                "producto-agregado-exito"               => "Producto Agregado con éxito al carrito",
                                                "producto-agregado-error"               => "Disculpa, hubo un error y el producto no se pudo agregar",
                                                "msj-carrito"                           => "Completa tu carro de pedidos y envialo, en poco tiempo nos pondremos en contacto contigo",
                                                "total"                                 => "Total",
                                                "seguir-comprando"                      => "Seguir Comprando",
                                                "no-hay-productos-carrito"              => "No hay productos en su Carrito",
                                                "cargue-productos"                      => "Para enviar la solicitud de cotización debe cargar productos al carrito",
                                                "solicitar-cotizacion"                  => "Solicitar Cotización",
                                                "formulario-solicitud"                  => "Formulario de Solicitud",
                                                "solicitud-cotizacion-exito"            => "La solicitud de cotización se envio con éxito",
                                                "solicitud-cotizacion-error"            => "Disculpa, hubo un error y la solicitud de cotización no se pudo enviar, intenta de nuevo mas tarde",
                                                "obras"                                 => "Obras",
                                                "obras-similares"                       => "Obras Similares",
                                                "visitas"                               => "Visitas",
                                                "construccion"                          => "Construcción",
                                                "remodelacion"                          => "Remodelación",
                                                "ventadeproductos"                      => "Venta de Productos",
                                                "asesoria"                              => "Asesoria",
                                                "conoce"                                => "Conoce",
                                                "nuestros-servicios"                    => "Nuestros Servicios",
                                                "nuestras-obras"                        => "Nuestras Obras",
                                                "te-presentamos"                        => "Te Presentamos",
                                                "nuestros-productos"                     => "Nuestros Productos Destacados",
                                                "filtra-por-categoria"                  => "Filtra por Categoria",
                                                "ingrese-nombre"                        => "Ingrese su Nombre",
                                                "ingrese-email"                         => "Ingrese su Email",
                                                "ingrese-telefono"                      => "Ingrese su Teléfono",
                                                "ingrese-mensaje"                       => "Ingrese su Mensaje",
                                                "ingrese-rif"                           => "Ingrese su Rif",
                                                "mensaje-footer"                        => "Todos los logos usados en esta web son marcas registradas de cada fabricante, su uso en esta pagina es solo para promover sus productos o para indicar la venta de los mismos.",
                                                "deseas-saber-nosotros"                 => "¿Deseas saber un poco mas sobre nosotros?",
                                                "contactanos"                           => "Contactanos",
                                                "nuestros-clientes"                     => "Nuestros Clientes",
                                                "completa-formulario-y"                 => "Completa el formulario y",
                                                "ademas-puedes-contactarnos"            => "Ademas puedes contactarnos completando el siguiente formulario",
                                                "sin-productos-categoria"               => "Disculpa, en este momento no tenemos productos registrados en esta categoria",
                                                "nuestras-categorias"                   => "Nuestras Categorias",
                                                "registrate"                            => "Registrate",
                                                "tienda"                                => "Tienda",
                                                "mi-cuenta"                             => "Mi Cuenta",
                                                "checkOut"                             => "CheckOut",
                                                "create-una-cuenta"                    => "Crea una Cuenta",
                                                "registrar"                            => "Registrar",
                                                "terminos-condiciones"                  => "Al hacer clic en 'Registrar' acepta los términos y condiciones",
                                                "estado"                                => "Estado",
                                                "contrasena"                            => "Contraseña",
                                                "seleccione-pais"                       => "Seleccione un País",
                                                "codigo"                                => "Codigo",
                                                "numero"                                => "Numero",
                                                "registro-exitoso"                      => "Felicidades, su registro en Sporthouse ha sido exitoso!",
                                                "email-existe"                          => "Disculpe, este email ya existe",
                                                "registro-error"                        => "Disculpe, su registro no se pudo completar, intente de nuevo",
                                                "contactanos"                           => "Contactanos",
                                                "mensaje-exitoso"                       => "El mensaje fue enviado exitosamente",
                                                "mensaje-error"                       => "Disculpe, su mensaje no pudo ser enviado, intente de nuevo mas tarde",
                                                "error-nombre"                          => "Disculpe debe escribir un nombre",
                                                "error-email"                          => "Disculpe debe escribir un email",
                                                "error-mensaje"                          => "Disculpe debe escribir un mensaje",
                                                "error-codigo"                          => "Disculpe debe escribir un código de telefono",
                                                "error-numero"                          => "Disculpe debe escribir un número de telefono",
                                                "error-rifcedula"                          => "Disculpe debe escribir un numero de cédula o rif",
                                                "error-estado"                          => "Disculpe debe escribir un estado",
                                                "error-clave"                          => "Disculpe debe escribir una clave",
                                                "error-pais"                            => "Disculpe debe seleccionar un país",
                                                "error-direccion"                          => "Disculpe debe escribir una dirección",
                                                "producto-detalle"                        => "Detalle del Producto",
                                                "modelo"                                => "Modelo",
                                                "marca"                                 => "Marca",
                                                "comprar-ahora"                         => "Comprar Ahora",
                                                "nuevos-clientes"                       => "Nuevos Clientes",
                                                "clientes-registrados"                  => "Clientes Registrados",
                                                "continuar"                  => "Continuar",
                                                "login"                  => "Iniciar Sesión",
                                                "texto-login"                  => "Por favor hacer clic para iniciar sesión",
                                                "olvido-contrasena"                  => "¿Olvidaste tu contraseña?",
                                                "login-no-existe"                  => "Los datos de acceso ingresados no se encuentran registrados en el sistema",
                                                "login-bloqueado"                  => "Disculpa el usuario con el cual intentas ingresar se encuentra bloqueado",
                                                "login-exito"                  => "Bienvenido a Sporthouse, puede continuar navegando a traves de la web!",
                                                "login-error"                  => "Disculpe, Ocurrio un error al momento de intentar iniciar sesión, por favor intenta de nuevo mas tarde",
                                                "mostrar"                  => "Mostrar",
                                                "por-pagina"                  => "Por página",
                                                "paginas"                  => "Páginas",
                                                "lista-busqueda"                  => "Lista de Búsqueda",
                                                "Marca"                  => "Marca",
                                                "anio"                  => "Año",
                                                "buscar"                  => "Buscar",
                                                "carrito-compras"                  => "Carrito de compras",
                                                "forma-pago"                  => "Todos tus pedidos pueden ser pagados a través de mercado pago y paypal! ",
                                                "completar-pago"                  => "Debes Iniciar Sesión para completar tu pago ",
                                                "ingresa-aqui"                  => "Ingresa Aqui!",
                                                "cerrar-sesion"                  => "Cerrar Sesión",
                                                "texto-agregar-carrito"                  => "Este producto sera agregado a la lista del carrito de compras",
                                                "texto-no-pedidos"                  => "Usted no tiene pedidos asociados a su cuenta.",
                                                "pedido-numero"                  => "Pedido Número",
                                                "pedido-estatus"                  => "Estatus del Pedido",
                                                "tus-productos"                  => "Tus Productos",
                                                "como-comprar"                  => "Como Comprar",
                                                "texto-como-comprar"                  => "Te enseñamos como comprar...",
                                                "mi-carrito"                  => "Ver Mi Carrito de Compra",
                                                );
		
		
		if($CI->session->userdata("idi") == "eng"){
			return $english[$eti];	
		}else{
			return $spaning[$eti];	
		}
		
	}
	
	


}

/* End of file array_helper.php */
/* Location: ./system/helpers/array_helper.php */